<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu primeiro projeto PHP</title>
</head>
<body>
    <?php
    $string = "Curso na DIO";
    ?>
    <h4> Essa é uma variável do tipo string, para implementar uma variável utilizamos aspas simples ('') ou duplas (""):
    <?php
    echo $string

    ?>
</body>
</html>